import { Instrument_Serif } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';

const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: ['400'], // '400' para normal
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#e6d6b8' }} className={instrumentSerif.className}>
        <Navbar /> {/* 2. Añadir el Navbar aquí */}
        {children}
      </body>
    </html>
  );
}
